"""Event-grouped splits and fold-plan APIs (DWCS-302)."""

from mma_model.modeling.splits import (
    EventGroup,
    FoldKind,
    FoldMetadata,
    FoldPlan,
    FoldRole,
    HoldoutLockedError,
    SplitCard,
    SplitError,
    build_fold_plan,
    cards_from_manifest,
    cards_from_session,
    group_cards,
    inspect_folds,
    outer_folds,
    protocol_fixture_cards,
    render_fold_plan,
    sealed_holdout_folds,
    sensitivity_membership,
    tuning_folds,
    validation_folds,
    verify_fold_plan,
)

__all__ = [
    "EventGroup",
    "FoldKind",
    "FoldMetadata",
    "FoldPlan",
    "FoldRole",
    "HoldoutLockedError",
    "SplitCard",
    "SplitError",
    "build_fold_plan",
    "cards_from_manifest",
    "cards_from_session",
    "group_cards",
    "inspect_folds",
    "outer_folds",
    "protocol_fixture_cards",
    "render_fold_plan",
    "sealed_holdout_folds",
    "sensitivity_membership",
    "tuning_folds",
    "validation_folds",
    "verify_fold_plan",
]
